### ISSUE TITLE
If ember-cli project is not in same folder as .git, index key posts as index:undefined

### ISSUE THREAD

**Issue by EmergentBehavior** [achambers/ember-cli-deploy-original#26]
I have a project where my ember client setup is in a sub-folder which does not contain the `.git` folder so I think ember-cli-deploy can't find the commit hashes.

I think you could get around this by being able to specify the git location in a .env file.

**Comment by achambers** [comment]
Coolio.  Thanks @EmergentBehavior.  This is a constant work in progress so will cater for this scenario shortly.  Once again, I'm happy to merge in a PR if you have fixed yourself.  Otherwise, will put it on the list.

**Comment by EmergentBehavior** [comment]
I can give a PR a go for this one.

**Comment by EmergentBehavior** [comment]
Okay, I got something working on my end. Will submit PR shortly.

**Comment by EmergentBehavior** [comment]
Since my changes were merged and there were subsequent improvements am closing this issue.
