### ISSUE TITLE
ember deploy:assets

### ISSUE THREAD

**Issue by achambers** [achambers/ember-cli-deploy-original#3]

**Comment by tigrish** [comment]
I'm a bit unsure about how to run this correctly. With the following command, I just get a list of the passed in options spit out :

```
ember deploy:assets --s3-access-key-id KEYID --s3-secret-access-key SECRET_KEY --s3-bucket-name BUCKET_NAME
```

Am I doing something totally wrong here?

**Comment by tigrish** [comment]
Soz, just realised that the PR for this hasn't been merged.

**Comment by achambers** [comment]
Hi @tigrish.  Only just noticed your comments here.  Sorry for the late reply.  Just about to merge in to master now so if you update shortly you should be good to go

**Comment by tigrish** [comment]
No worries, thanks @achambers

**Comment by achambers** [comment]
Anytime mate, /cc @tigrish
