### ISSUE TITLE
Potential configuration file formatting issue

### ISSUE THREAD

**Issue by EmergentBehavior** [achambers/ember-cli-deploy-original#44]
Sorry to be a pain, I feel like I'm making a number of issues lately :)

`ember-cli-deploy` was able to find my specified configuration file, but it wasn't reading it properly. I had to rename the config file extension from `.js` to `.json` and wrap everything in double quotes for it to work properly.

**Comment by achambers** [comment]
No probs mate. That's how we make this addon better :) 

Can you post an example if the config file that didn't work please? I suspect I know the problem as there is a typo in the README for which I just saw a PR to fix. 

You shouldn't need to make the changes you mentioned.

**Comment by EmergentBehavior** [comment]
I basically used the example you had posted on the front of the readme.

**Comment by achambers** [comment]
Yep.  Thought so.  Have a look at this fix (#46) to the README.  This will fix your problem.  Will be merging this PR is shortly.

**Comment by EmergentBehavior** [comment]
Ah, yes that would have helped :).

**Comment by achambers** [comment]
Thanks for pointing that out.  That's the beauty of collaborating eh?  I'll
fix that up shortly mate.  Thanks.
