### ISSUE TITLE
Asset url rewriting

### ISSUE THREAD

**Issue by jbrown** [achambers/ember-cli-deploy-original#48]
I was able to successfully deploy index to a fuzzy-wookie server and my assets to S3. But shouldn't the asset urls in index be rewritten to point to S3? Am I missing something?

**Comment by achambers** [comment]
You are.  But only because there is something I should have put in the README...but forgot ;)

You need to modify your Brocfile.js as follows:

``` javascript
var app = new EmberApp({
  fingerprint: {
    prepend: '<the base url to your assets>'
  }
});
```
