### ISSUE TITLE
List current index.html versions

### ISSUE THREAD

**Issue by achambers** [achambers/ember-cli-deploy-original#54]
ember deploy:versions

**Comment by pavloo** [comment]
Hey @achambers, i'd love to work on this feature. If you don't have personal plans on implementing this, please put any of your thoughts/wishes which your think must be taken into account before the elaboration starts. Thanks.

**Comment by achambers** [comment]
Hi @sol1dus, that's great.  I am planning on working on it but feel free to have a crack at it in the meantime.  Not sure when I'll get to it.

Happy to carry on a discussion about the feature.  If you can please raise a PR early on against the `next-release-v0.0.6` branch then I can keep up to date with the changes you're making and we can keep track of a discussion there.  Please push your changes to your PR branch regularly.  We can clean them up to make more sense once the feature is ready to roll.

Off the top of my head, things to keep in mind are:
- raise PR against `next-release-v0.0.6` branch (as mentioned above)
- Understand the changes that have been made around index adapters before starting this.  There shouldn't really be much logic needed in this repo as the bulk of it should be in the adapter.
- At the moment there is only one index adapter (Redis) which is here: https://github.com/achambers/ember-cli-deploy-redis-index-adapter .  It already has some logic to list the versions.  However, it needs a public api method to be added.  Please update this repo as well because `ember-cli-deploy` uses this adapter by default.
- Therefore you will need to update the version of `ember-cli-deploy-redis-index-adapter` that `ember-cli-deploy` points to so they are in sync.
- Tests tests tests.....No changes will be merged without them

Any questions, add them to the PR and we can discuss.

Great to have you contributing to the project mate.

**Comment by pavloo** [comment]
@achambers thank you
