### ISSUE TITLE
ember activate breaking changes?

### ISSUE THREAD

**Issue by EmergentBehavior** [achambers/ember-cli-deploy-original#59]
After upgrading to v0.0.5, I noticed two breaking changes:
- Instead of `index:<some_hash>` the keys are now `<your_project>:<some_hash>`.
- `ember activate <some_hash>` now seems to replace the value of `<your_project>:current` with  < some_hash > instead of the actual HTML content. 

If these are now expected behaviors, there should be some note indicating such as I was confused why my existing code wasn't working.

**Comment by achambers** [comment]
Oh crap.  Sorry mate.  I have been trying to keep the releases up to date.  But I accidently marked the PR for that change as [ENHANCEMENT] instead of [BREAKING CHANGE].  Have fixed it up now.

https://github.com/achambers/ember-cli-deploy/releases/tag/v0.0.5

**Comment by achambers** [comment]
Also, I am yet to update https://github.com/achambers/fuzzy-wookie to work with these changes

**Comment by EmergentBehavior** [comment]
Good to know :). The changes do make my example in #28 invalid, though. Don't have time to make a docker, etc. now but I can post a new example somewhere or in a wiki if you think it'd be helpful.

**Comment by achambers** [comment]
My thoughts are that while I've provided an express app to serve the index.html, anyone could provide any other means. If you did that, we could reference it in the README. In planning on writing a ruby version as well.

**Comment by achambers** [comment]
Can we close this issue now?

**Comment by EmergentBehavior** [comment]
Sure
