### ISSUE TITLE
Handle the case when there is no git repo

### ISSUE THREAD

**Issue by pavloo** [achambers/ember-cli-deploy-original#64]
The case when `ember:deploy` tasks are executed against a project, which doesn't have a _git repository_, must be handled. Of course, it's not a use case, but still we need to cut off such things. For instance, now if we run `ember deploy:index` inside of a project without _git repo_, version key with the value `fatal: Not a git repository (or any of the parent directories): .git` is still created in Redis.

**Comment by achambers** [comment]
Yep. Good shout. Although, you probably shouldn't be using that particular redis adapter if that's the case. Either way, we should at least fail gracefully. 

This isnt actually an ember-cli-deploy issue. It resides with the adapter. Can you please close and re-raise on the correct repo?

**Comment by pavloo** [comment]
Closing in favor of this https://github.com/achambers/ember-cli-deploy-redis-index-adapter/issues/6.
