### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by netcurate** [achambers/ember-cli-deploy-original#69]
Hi,

Ember-cli-deploy doesn't install on Windows environment. The issue is with gitty which requires either Linux or OSX environment.

Has anyone been able to install this on Windows?

**Comment by BryanCrotaz** [comment]
Confirmed

**Comment by netcurate** [comment]
Well, just not this issue but several other issues, big and small forced us to finally move from Windows to OSX .. and we are not repenting the decision :)
